# Generated by Django 4.1 on 2022-08-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='fk',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fk',
            new_name='image',
        ),
    ]
